### ISSUE TITLE
com.thebluealliance.spectrum.SpectrumPreferenceCompat cannot be cast to android.preference.Preference

### ISSUE THREAD

**Issue by ashleypeacock** [the-blue-alliance/spectrum#25]
```
FATAL EXCEPTION: main
 Process: uk.ac.ucl.pcareader, PID: 5394
java.lang.RuntimeException: Unable to resume activity {uk.ac.ucl.pcareader/uk.ac.ucl.pcareader.reading.ReadingActivity}: java.lang.ClassCastException: com.thebluealliance.spectrum.SpectrumPreferenceCompat cannot be cast to android.preference.Preference
 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4006)
 at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4037)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3244)
at android.app.ActivityThread.access$1000(ActivityThread.java:197)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6873)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by: java.lang.ClassCastException: com.thebluealliance.spectrum.SpectrumPreferenceCompat cannot be cast to android.preference.Preference
at android.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:45)
 at android.preference.GenericInflater.rInflate(GenericInflater.java:488)
at android.preference.GenericInflater.inflate(GenericInflater.java:326)
at android.preference.GenericInflater.inflate(GenericInflater.java:263)
at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:272)
at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:300)
 at uk.ac.ucl.pcareader.fragments.SettingsPreferenceFragment.onCreate(SettingsPreferenceFragment.java:66)
at android.app.Fragment.performCreate(Fragment.java:2075)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:868)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1082)
at android.app.BackStackRecord.run(BackStackRecord.java:834)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467)
at android.app.Activity.performResume(Activity.java:6665)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3995)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4037) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3244) 
  at android.app.ActivityThread.access$1000(ActivityThread.java:197) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:145) 
at android.app.ActivityThread.main(ActivityThread.java:6873) 
at java.lang.reflect.Method.invoke(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:372) 
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
```

Error is caused in addPreferencesFromResource.

**Comment by rabross** [comment]
Did you try using SpectrumPreference instead of SpectrumPreferenceCompat?

**Comment by ashleypeacock** [comment]
Oooh shit. Thanks for the rapid reply you've saved me a few hours of stupid.

**Comment by ashleypeacock** [comment]
Hero thankyou :)
